{{- if eq .Values.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  {{- $args := dict "dot" . "component" "adapter-lora-vertx" "name" "adapter-lora-vertx" }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ .Release.Name }}-adapter-lora-vertx
{{- end }}
