---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: hono-adapter-http-vertx
  name: hono-adapter-http-vertx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "hono.name" . }}
      app.kubernetes.io/component: hono-adapter-http-vertx
  template:
    metadata:
      labels:
        {{- include "hono.std.labels" . | nindent 8 }}
        app.kubernetes.io/component: hono-adapter-http-vertx
    spec:
      {{- if eq .Values.jaeger.enabled true }}
      initContainers:
        - name: wait-for-jaeger-agent
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup {{ .Values.jaeger.agentHost }}; do echo waiting for {{ .Values.jaeger.agentHost }}; sleep 2; done;']
      {{- end }}
      containers:
      - image: {{ .Values.honoContainerRegistry }}/eclipse/hono-adapter-http-vertx:{{ .Values.honoImageTag }}
        imagePullPolicy: IfNotPresent
        name: eclipse-hono-adapter-http-vertx
        ports:
        - name: health
          containerPort: {{ .Values.healthCheckPort }}
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        securityContext:
          privileged: false
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:///etc/hono/
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: LOGGING_CONFIG
          value: classpath:logback-spring.xml
      {{- if eq .Values.jaeger.enabled true }}
        - name: JAEGER_SERVICE_NAME
          value: hono-adapter-http
        {{- range $key, $value := .Values.jaeger.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
      {{- end }}
        - name: _JAVA_OPTIONS
          value: "{{ .Values.defaultJavaOptions }}"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /etc/hono
          name: conf
          readOnly: true
        resources:
          limits:
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ .Values.healthCheckPort }}
            scheme: HTTPS
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.healthCheckPort }}
            scheme: HTTPS
          initialDelaySeconds: 10
      volumes:
      - name: conf
        secret:
          secretName: hono-adapter-http-vertx-conf
