{{- if eq .Values.platform "openshift" }}
apiVersion: v1
kind: Route
metadata:
  {{- $args := dict "dot" . "component" "adapter-http-vertx" "name" "adapter-http-vertx-sec" }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  port:
    targetPort: 8443
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ .Release.Name }}-adapter-http-vertx
{{- end }}
