apiVersion: v1
kind: Secret
metadata:
  name: hono-adapter-http-vertx-conf
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: hono-adapter-http-vertx
type: Opaque
stringData:
  "http-adapter.credentials": |
    {{- .Files.Get "example/http-adapter.credentials" | nindent 4 }}
  "application.yml": |
    {{- .Files.Get "config/hono-adapter-http-vertx-config.yml" | nindent 4 }}
data:
  "http-adapter-key.pem": {{ .Files.Get "hono-demo-certs-jar/http-adapter-key.pem" | b64enc }}
  "http-adapter-cert.pem": {{ .Files.Get "hono-demo-certs-jar/http-adapter-cert.pem" | b64enc }}
  "trusted-certs.pem": {{ .Files.Get "hono-demo-certs-jar/trusted-certs.pem" | b64enc }}
