{{- if eq .Values.platform "openshift" }}
---
apiVersion: v1
kind: Route
metadata:
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: hono-adapter-http-vertx
  name: hono-adapter-http-vertx-sec
spec:
  port:
    targetPort: 8443
  tls:
    termination: passthrough
  to:
    kind: Service
    name: hono-adapter-http-vertx
{{- end }}
