---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: amqp-messaging-network-router
  name: ${hono.amqp-network.service}-ext
spec:
  ports:
  - name: amqps
    port: 15671
    protocol: TCP
    targetPort: amqps
    nodePort: 30671
  - name: amqp
    port: 15672
    protocol: TCP
    targetPort: amqp
    nodePort: 30672
  selector:
    app.kubernetes.io/name: {{ template "hono.name" . }}
    app.kubernetes.io/component: amqp-messaging-network-router
{{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" ) }}
  type: LoadBalancer
{{ else }}
  type: NodePort
{{- end }}
