{{- if .Values.amqpMessagingNetworkDeployExample -}}
apiVersion: v1
kind: Secret
metadata:
  {{- $args := dict "dot" . "component" "amqp-messaging-network-router" "name" "dispatch-router-conf" }}
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  "qdrouterd-with-broker.json": |
    {{- include "hono.qdrouterd-with-broker.json" . | nindent 4 }}
data:
  "qdrouter-key.pem": {{ .Files.Get "hono-demo-certs-jar/qdrouter-key.pem" | b64enc }}
  "qdrouter-cert.pem": {{ .Files.Get "hono-demo-certs-jar/qdrouter-cert.pem" | b64enc }}
  "trusted-certs.pem": {{ .Files.Get "hono-demo-certs-jar/trusted-certs.pem" | b64enc }}
{{- end }}
