---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: amqp-messaging-network-router
  name: ${hono.amqp-network.service}
spec:
  ports:
  - port: 5673
    protocol: TCP
    targetPort: internal
  selector:
    app.kubernetes.io/name: {{ template "hono.name" . }}
    app.kubernetes.io/component: amqp-messaging-network-router
