{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  {{- $args := dict "dot" . "component" "dashboard" "name" "grafana-datasources" }}
  {{- include "hono.metadata" $args | nindent 2 }}
    grafana_datasource: "1"
type: Opaque
stringData:
  hono-datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: hono_metrics
      version: 1
      type: prometheus
      access: proxy
      orgId: 1
    {{- if .Values.prometheus.createInstance }}
      url: http://{{ template "hono.prometheus.server.fullname" . }}:9090
    {{- else }}
      url: http://{{ required "No Prometheus server host set" .Values.prometheus.host }}:{{ default "9090" .Values.prometheus.port }}
    {{- end }}
      basicAuth: false
      isDefault: true
      editable: true
{{- end }}
