apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- $args := dict "dot" . "component" "service-device-registry" "name" "service-device-registry" }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.deviceRegistry.storageClass }}
  storageClassName: {{ .Values.deviceRegistry.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: 1Mi
