---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: hono-service-device-registry
  name: registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
