{{- if eq .Values.platform "openshift" }}
apiVersion: v1
kind: Route
metadata:
  {{- $args := dict "dot" . "component" "service-device-registry" "name" "service-device-registry-https" }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  port:
    targetPort: 8443
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ .Release.Name }}-service-device-registry
{{- end }}
