apiVersion: v1
kind: Secret
metadata:
  name: hono-service-auth-conf
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: hono-service-auth
type: Opaque
stringData:
  "permissions.json": |
    {{- .Files.Get "example/example-permissions.json" | nindent 4 }}
  "application.yml": |
    {{- .Files.Get "config/hono-service-auth-config.yml" | nindent 4 }}
data:
  "auth-server-key.pem": {{ .Files.Get "hono-demo-certs-jar/auth-server-key.pem" | b64enc }}
  "auth-server-cert.pem": {{ .Files.Get "hono-demo-certs-jar/auth-server-cert.pem" | b64enc }}
  "trusted-certs.pem": {{ .Files.Get "hono-demo-certs-jar/trusted-certs.pem" | b64enc }}
