{{- $args := dict "dot" . "component" "service-auth" "name" "service-auth-conf" -}}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  permissions.json: |
    {{- .Files.Get "example/example-permissions.json" | nindent 4 }}
  application.yml: |
    hono:
      app:
        maxInstances: 1
      auth:
        amqp:
          bindAddress: 0.0.0.0
          keyPath: /etc/hono/key.pem
          certPath: /etc/hono/cert.pem
          trustStorePath: /etc/hono/trusted-certs.pem
          insecurePortBindAddress: 0.0.0.0
          insecurePortEnabled: true
        svc:
          permissionsPath: file:///etc/hono/permissions.json
      {{- include "hono.healthServerConfig" nil | nindent 6 }}
data:
  key.pem: {{ .Files.Get "hono-demo-certs-jar/auth-server-key.pem" | b64enc }}
  cert.pem: {{ .Files.Get "hono-demo-certs-jar/auth-server-cert.pem" | b64enc }}
  trusted-certs.pem: {{ .Files.Get "hono-demo-certs-jar/trusted-certs.pem" | b64enc }}
