---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: hono-service-auth
    hono-metrics: prometheus
  name: ${hono.auth.service}
spec:
  ports:
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: amqps
  selector:
    app.kubernetes.io/name: {{ template "hono.name" . }}
    app.kubernetes.io/component: hono-service-auth
