{{- if and .Values.prometheus.createInstance .Values.adapters.kura.enabled }}
{{- $args := dict "dot" . "component" "adapter-kura" "name" "adapter-kura" }}
{{- include "hono.headless.service" $args }}
{{ end }}
