apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "adapter-kura" "name" "adapter-kura" }}
  {{- include "hono.metadata" $args | nindent 2 }}
    hono-metrics: prometheus
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
    nodePort: 31884
  - name: secure-mqtt
    port: 8883
    protocol: TCP
    targetPort: secure-mqtt
    nodePort: 30884
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
{{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" ) }}
  type: LoadBalancer
{{ else }}
  type: NodePort
{{- end }}
