{{- if eq .Values.platform "openshift" }}
---
apiVersion: v1
kind: Route
metadata:
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: hono-adapter-kura
  name: hono-adapter-kura
spec:
  port:
    targetPort: 1883
  to:
    kind: Service
    name: hono-adapter-kura
{{- end }}
