---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "hono.name" . }}
      app.kubernetes.io/component: metrics
  resources:
    requests:
      memory: 400Mi
  securityContext: {}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hono
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "hono.name" . }}
      hono-metrics: prometheus
  endpoints:
    - scheme: HTTPS
      targetPort: {{ .Values.monitoring.prometheus.port }}
      path: /prometheus
      interval: 5s
      tlsConfig:
        insecureSkipVerify: true
