#
# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
hono:
  app:
    maxInstances: 1
    startupTimeout: 90
  healthCheck:
    port: ${vertx.health.port}
    bindAddress: 0.0.0.0
    keyPath: /run/secrets/command-router-key.pem
    certPath: /run/secrets/command-router-cert.pem
  auth:
    host: ${hono.auth.service}${service.suffix}
    port: 5671
    trustStorePath: /run/secrets/trusted-certs.pem
    name: 'Hono Command Router'
    supportedSaslMechanisms: "PLAIN"
    validation:
      certPath: /run/secrets/auth-server-cert.pem
  commandRouter:
    amqp:
      bindAddress: 0.0.0.0
      keyPath: /run/secrets/command-router-key.pem
      certPath: /run/secrets/command-router-cert.pem
      insecurePortBindAddress: 0.0.0.0
      insecurePortEnabled: true
    cache:
      embedded:
        configurationFile: "/etc/hono/command-router-cache-config.xml"
  registration:
    name: 'Hono Command Router'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/command-router.credentials
  tenant:
    name: 'Hono Command Router'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/command-router.credentials
  command:
    name: 'Hono Command Router'
    host: ${hono.amqp-network.service}${service.suffix}
    port: 5673
    amqpHostname: hono-internal
  vertx:
    preferNative: true

quarkus:
  log:
    console:
      color: true
    level: INFO
    category:
      "org.eclipse.hono":
        level: INFO
      "org.eclipse.hono.authentication.impl":
        level: INFO
      "org.eclipse.hono.commandrouter":
        level: INFO
      "org.eclipse.hono.deviceconnection.infinispan.client":
        level: INFO
      "org.infinispan":
        level: INFO
  vertx:
    prefer-native-transport: true
