{{- if eq .Values.platform "openshift" }}
---
apiVersion: v1
kind: Route
metadata:
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: hono-adapter-amqp-vertx
  name: hono-adapter-amqp-vertx
spec:
  port:
    targetPort: 5672
  to:
    kind: Service
    name: hono-adapter-amqp-vertx
{{- end }}
