---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: hono-adapter-amqp-vertx
    hono-metrics: prometheus
  name: hono-adapter-amqp-vertx
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: amqp
    nodePort: 32672
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: amqps
    nodePort: 32671
  selector:
    app.kubernetes.io/name: {{ template "hono.name" . }}
    app.kubernetes.io/component: hono-adapter-amqp-vertx
{{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" ) }}
  type: LoadBalancer
{{ else }}
  type: NodePort
{{- end }}
