---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "hono.std.labels" . | nindent 4 }}
    app.kubernetes.io/component: hono-adapter-mqtt-vertx
    hono-metrics: prometheus
  name: hono-adapter-mqtt-vertx
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
    nodePort: 31883
  - name: secure-mqtt
    port: 8883
    protocol: TCP
    targetPort: secure-mqtt
    nodePort: 30883
  selector:
    app.kubernetes.io/name: {{ template "hono.name" . }}
    app.kubernetes.io/component: hono-adapter-mqtt-vertx
{{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" ) }}
  type: LoadBalancer
{{ else }}
  type: NodePort
{{- end }}
  